package io.gen2spring.mcp.domain.error;

public enum GeneratorErrorCode {
    SPEC_FILE_UNSUPPORTED,
    SPEC_TOO_LARGE,
    SPEC_PARSE_FAILED,
    SPEC_REFERENCE_UNRESOLVED,
    SPEC_VERSION_UNSUPPORTED,
    OPERATION_ID_DUPLICATED,
    OPERATION_UNSUPPORTED,
    SECRET_EXPOSURE_DETECTED,
    TARGET_PROFILE_NOT_FOUND,
    TARGET_COMBINATION_UNSUPPORTED,
    SOURCE_GENERATION_FAILED,
    COMPILE_TIMEOUT,
    COMPILE_FAILED,
    APPLICATION_CONTEXT_FAILED,
    MCP_INITIALIZE_FAILED,
    MCP_TOOLS_LIST_FAILED,
    ARTIFACT_PACKAGE_FAILED,
    INTERNAL_ERROR
}
